name: Reveil Streamlit
on:
  schedule:
    - cron: "0 8 * * *"  # Tous les jours Ã  8h00
  workflow_dispatch:      # Permet le lancement manuel

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL
        run: curl -I https://rtcdashboard-gnjjifvatpjst4ktbfsspu.streamlit.app/